name: Polymarket Tracker

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Show state.json BEFORE
        run: |
          echo "=== state.json ANTES ==="
          cat state.json || echo "Arquivo não existe"
      
      - name: Run tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          YOUR_BANKROLL: ${{ secrets.YOUR_BANKROLL }}
        run: python tracker.py
      
      - name: Show state.json AFTER
        run: |
          echo "=== state.json DEPOIS ==="
          cat state.json || echo "Arquivo não existe"
      
      - name: Commit and push state changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add state.json
          
          if git diff --staged --quiet; then
            echo "Nenhuma mudança para commitar"
          else
            git commit -m "Update tracker state [skip ci]"
            git push
          fi
